export const data = [
  {
    id: 1,
    type: "To Do",
    subject: "Sample",
    Assigned: "Ravi Kumar",
    DueDate: "17 Nov 2021",
    Status: "Not Started",
  },
  {
    id: 2,
    type: "To Do",
    subject: "Sample",
    Assigned: "Anand Pal",
    DueDate: "17 Nov 2021",
    Status: "Not Started",
  },
  {
    id: 3,
    type: "To Do",
    subject: "Sample",
    Assigned: "Jayram Ramesh",
    DueDate: "17 Nov 2021",
    Status: "Not Started",
  },
  {
    id: 4,
    type: "To Do",
    subject: "Sample",
    Assigned: "Allan Gomez",
    DueDate: "17 Nov 2021",
    Status: "Not Started",
  },
];

export const StatusData = [
  {
    id: 1,
    productStatus: "Informed Product Features",
    date: "2022-08-04",
    time: "06:49 AM",
    liveStatus: "You Contacted with",
    employeename: "Charles Gomez",
  },
  {
    id: 2,
    productStatus: "Send Product Brochure",
    date: "2022-08-05",
    time: "07:49 AM",
    liveStatus: "You Contacted with",
    employeename: "Arun Var",
  },
  {
    id: 3,
    productStatus: "Send Product Brochure",
    date: "2022-08-04",
    time: "06:49 AM",
    liveStatus: "You Contacted with",
    employeename: "Arun Var",
  },
  {
    id: 4,
    productStatus: "Informed Product Features",
    date: "2021-08-04",
    time: "06:49 AM",
    liveStatus: "You Contacted with",
    employeename: "Arun Var",
  },
  {
    id: 5,
    productStatus: "Informed Product Features",
    date: "2022-08-01",
    time: "06:49 AM",
    liveStatus: "You Contacted with",
    employeename: "Charles Gomez",
  },
];
